import AppKit
import Foundation

enum ClipboardHistoryRetention: String, CaseIterable, Codable {
    case sessionOnly
    case oneDay
    case sevenDays
    case thirtyDays

    var displayName: String {
        switch self {
        case .sessionOnly: return "Session only"
        case .oneDay: return "1 day"
        case .sevenDays: return "7 days"
        case .thirtyDays: return "30 days"
        }
    }

    var persistsToDisk: Bool { self != .sessionOnly }

    fileprivate var maximumAge: TimeInterval? {
        switch self {
        case .sessionOnly: return nil
        case .oneDay: return 86_400
        case .sevenDays: return 7 * 86_400
        case .thirtyDays: return 30 * 86_400
        }
    }
}

enum ClipboardHistoryPrivacyPolicy {
    private static let blockedPasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func shouldCapture(types: [NSPasteboard.PasteboardType]) -> Bool {
        blockedPasteboardTypes.isDisjoint(with: types.map(\.rawValue))
    }

    /// Pinned items are intentionally exempt from time-based retention until the user
    /// unpins or explicitly deletes them. Session-only affects persistence, not the
    /// current in-memory session.
    static func retainedItems(
        _ items: [ClipboardHistoryItem],
        retention: ClipboardHistoryRetention,
        now: Date = Date()
    ) -> [ClipboardHistoryItem] {
        guard let maximumAge = retention.maximumAge else { return items }
        let cutoff = now.addingTimeInterval(-maximumAge)
        return items.filter { $0.isPinned || $0.timestamp >= cutoff }
    }

    /// The capacity is a soft total limit: pinned items are never evicted. They
    /// consume available slots first, and the newest unpinned items fill any
    /// remaining slots. If pinned items exceed the limit, all remain persisted.
    static func enforcingCapacity(
        _ items: [ClipboardHistoryItem],
        maximumCount: Int
    ) -> [ClipboardHistoryItem] {
        guard maximumCount >= 0 else { return items.filter(\.isPinned) }
        let pinnedCount = items.filter(\.isPinned).count
        let unpinnedSlots = max(0, maximumCount - pinnedCount)
        let retainedUnpinnedIDs = Set(
            items.filter { !$0.isPinned }
                .sorted { $0.timestamp > $1.timestamp }
                .prefix(unpinnedSlots)
                .map(\.id)
        )
        return items.filter { $0.isPinned || retainedUnpinnedIDs.contains($0.id) }
    }

    /// Sensitive filtering is deliberately not controlled by a preference. A missing
    /// or reset preference therefore cannot disable this defense-in-depth check.
    static func containsSensitiveData(_ content: String) -> Bool {
        let patterns = [
            "(?i)(api[_-]?key|apikey|access[_-]?key)[\\s:=\"']+([a-zA-Z0-9_\\-]{20,})",
            "(?i)(secret[_-]?key|secretkey)[\\s:=\"']+([a-zA-Z0-9_\\-]{20,})",
            "(?i)(AKIA[0-9A-Z]{16})",
            "eyJ[a-zA-Z0-9_\\-]+\\.eyJ[a-zA-Z0-9_\\-]+\\.[a-zA-Z0-9_\\-]+",
            "gh[pousr]_[a-zA-Z0-9]{36,255}",
            "-----BEGIN (RSA|DSA|EC|OPENSSH|PGP) PRIVATE KEY-----",
            "\\b(?:\\d[ -]*?){13,19}\\b",
            "(?i)(bearer|oauth)[\\s:]+([a-zA-Z0-9_\\-\\.]{20,})",
            "(?i)(token|auth)[\\s:=\"']+([a-zA-Z0-9_\\-\\.]{32,})",
            "(?i)(password|pwd)[\\s:=\"']+([^\\s\"';,]{6,})",
            "(?i)(mongodb|mysql|postgres|postgresql)://[^\\s\"']+:[^\\s\"']+@",
        ]

        let range = NSRange(content.startIndex..., in: content)
        return patterns.contains { pattern in
            guard let regex = try? NSRegularExpression(pattern: pattern) else { return false }
            return regex.firstMatch(in: content, range: range) != nil
        }
    }
}

enum ClipboardLogMetadata {
    static func summary(for item: ClipboardHistoryItem) -> String {
        "\(item.type.displayName) item (\(item.content.utf8.count) bytes)"
    }
}

extension Notification.Name {
    static let clipboardHistoryDidClear = Notification.Name("ClipboardHistoryDidClear")
    static let clipboardPauseStateDidChange = Notification.Name("ClipboardPauseStateDidChange")
}

final class ClipboardPauseStateObserver {
    private let notificationCenter: NotificationCenter
    private var token: NSObjectProtocol?

    init(
        notificationCenter: NotificationCenter = .default,
        handler: @escaping (Bool) -> Void
    ) {
        self.notificationCenter = notificationCenter
        token = notificationCenter.addObserver(
            forName: .clipboardPauseStateDidChange,
            object: nil,
            queue: nil
        ) { notification in
            guard let isPaused = notification.userInfo?["isPaused"] as? Bool else { return }
            handler(isPaused)
        }
    }

    deinit {
        if let token { notificationCenter.removeObserver(token) }
    }
}
